config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :account, only: [ :show, :edit, :update ] do
    collection do
      get :cancel
      patch :privacy
    end
  end

  resources :posts, except: :show do
    collection do
      get :cancel
      get :my_posts
      get :onelayer
      post :daily_digest
    end
    resources :likes, only: [ :destroy, :create ]
  end

  resources :friendships, only: [ :index, :new, :create, :update ] do
    collection do
      get :pending_requests
      get :rejected_requests
      delete :cancel_request
      get :search
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :reciver, class_name: "User", foreign_key: "reciver_id"

  enum :friendship_status, { pending: 0, accepted: 1, rejected: 2 }

  validate :sender_and_receiver_cannot_be_same

  private

  def sender_and_receiver_cannot_be_same
    if sender_id == reciver_id
      errors.add("reciver can't be the same as sender")
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :add_friends_list, only: [ :new, :search ]
  before_action :friends_list, only: [ :index, :search ]

  def index; end

  def new; end

  def create
    @friendship = current_user.sent_friendships.create(reciver_id: params[:fid])
    receiver = User.find_by(id: params[:fid])

    if @friendship.persisted? && receiver.present?
      FriendRequestMailer.with(user: current_user, friend: receiver).new_request.deliver_now
    end
  end

  def update
    @friendship = current_user.sent_friendships.find_by(id: params[:id])  || current_user.received_friendships.find_by(id: params[:id])
    @update_success = @friendship&.update(friendship_status: params[:status].to_i)
     if @update_success && @friendship.accepted?
      sender = @friendship.sender
      receiver = @friendship.reciver
      FriendRequestMailer.with(user: sender, friend: receiver).request_accepted.deliver_now
     end
  end

  def pending_requests
    @pending_requests = User.where(id: current_user.pending_friends_ids).includes(:avatar_attachment)
  end

  def rejected_requests
    @rejected_requests = User.where(id: current_user.rejected_friends_ids).includes(:avatar_attachment)
  end

  def cancel_request
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
  end

  def search
    @input = params[:search].strip
    if params[:type] == "friends"
      @friends_list = @friends_list.where("users.username LIKE ? OR users.email = ?", "%#{@input}%", @input)

      render "index"
    else
      @add_friends_list = @add_friends_list.where("users.username LIKE ? OR users.email = ?", "%#{@input}%", @input)

      render "new"
    end
  end


private

  def add_friends_list
    @add_friends_list = User.where.not(id: current_user.accepted_friends_ids << current_user.id).includes(:avatar_attachment)
  end

  def friends_list
    @friends_list = User.where(id: current_user.accepted_friends_ids).includes(:avatar_attachment)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def turbo_reference_key(friendship, referer)
    page = referer.to_s.split("/").last

    case page
    when "new"
      "friends_#{friendship.sender_id}"
    when "pending_requests"
      "pendingpage_#{friendship.sender_id}"
    when "rejected_requests"
      "rejectedpage_#{friendship.sender_id}"
    else
      "accountpage_#{friendship.sender_id}"
    end
  end
end

app/views/friendships/_friendship_action.html.erb
<%= turbo_frame_tag "friendbutton_#{user.id}" do %>
  <% if friendship = current_user.sent_friendships.pending.find_by(reciver_id: user.id) || current_user.sent_friendships.rejected.find_by(reciver_id: user.id) %>
    <%= turbo_frame_tag "cancel_#{user.id}" do %>
      <%= button_to "Pending" %>
      <%= button_to "cancel request", cancel_request_friendships_path(id: friendship.id), method: :delete, params: { reciver_id: user.id } %>
    <% end %>
  <% elsif friendship = current_user.received_friendships.pending.find_by(sender_id: user.id) %>
    <%= button_to "accept", friendship_path(friendship.id, status: Friendship.friendship_statuses[:accepted]), method: :patch %>
    <%= button_to "reject", friendship_path(friendship.id, status: Friendship.friendship_statuses[:rejected]), method: :patch %>
  <% elsif Friendship.where(sender_id: current_user.id, reciver_id: user.id).or(Friendship.where(sender_id: user.id, reciver_id: current_user.id)).none? %>
    <%= turbo_frame_tag "fbutton_#{user.id}" do %>
      <%= button_to "Add Friend", friendships_path(fid: user.id), method: :post %>
    <% end %>
  <% end %>
<% end %>

app/views/friendships/_search.html.erb
<%= form_with url: search_friendships_path, method: :get do |f| %>
  <%= f.hidden_field :type, value: search_type %> 
  <%= f.text_field :search, value: params[:search] %>
  <%= f.submit "Search" %>
<% end %>

app/views/friendships/cancel_request.turbo_stream.erb
<%= turbo_stream.replace "cancel_#{params[:reciver_id]}" do%>
  <%= turbo_frame_tag "fbutton_#{params[:reciver_id]}" do %>
    <%= button_to "Add Friend", friendships_path(fid: params[:reciver_id]), method: :post %>
  <% end %>
<% end %>

app/views/friendships/create.turbo_stream.erb
<% friendship = current_user.sent_friendships.pending.find_by(reciver_id: params[:fid]) %>

<%= turbo_stream.replace "fbutton_#{params[:fid]}" do %>
  <%= turbo_frame_tag "cancel_#{params[:fid]}" do %>
      <%= button_to "Pending" %>
      <%= button_to "cancel request", cancel_request_friendships_path(id: friendship.id), method: :delete, params: { reciver_id: params[:fid] } %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_message %>

app/views/friendships/index.html.erb
<%= button_to "Add Friends", new_friendship_path, method: :get %>
<%= button_to "Pending Requests(#{current_user.pending_friends_ids.count})", pending_requests_friendships_path, method: :get %>
<%= button_to "Rejected List", rejected_requests_friendships_path, method: :get %>
<%= render partial: "search", locals: { search_type: "friends" } %>
<% @friends_list.each do |user| %>
  <%= image_tag url_for(user.avatar), class: "avatar" if user.avatar.attached? %>
  <%= link_to  user.name, account_path(user), method: :get%>
  <h1></h1>
<% end %>

app/views/friendships/new.html.erb
<%= render partial: "search", locals: { search_type: "add_friends" } %>
<% @add_friends_list.each do |user| %>
  <%= turbo_frame_tag "friends_#{user.id}" do %>
    <%= image_tag url_for(user.avatar), class: "avatar" if user.avatar.attached? %>
    <%= link_to  user.name, account_path(user.id), method: :get, data: { turbo_frame: "_top" } %>
    <h1></h1>
    <%= render partial: "friendship_action", locals: { user: user } %>
    <h1></h1>
  <% end %>
<% end %>

app/views/friendships/pending_requests.html.erb
<% if @pending_requests.count==0 %>
  <p>No Pending Requests </p>
<%end%>
<% @pending_requests.each do |user| %>
  <%= turbo_frame_tag "pendingpage_#{user.id}" do %>
    <%= image_tag url_for(user.avatar), class: "avatar" if user.avatar.attached? %>
    <%= link_to  user.name, account_path(user.id), method: :get, data: { turbo_frame: "_top" } %>
    <h1></h1>
    <% friendship = Friendship.where(reciver_id: current_user.id , sender_id: user.id).first %>
    <%= button_to "accept", friendship_path(friendship, status: Friendship.friendship_statuses[:accepted]), method: :patch %>
    <%= button_to "reject", friendship_path(friendship, status: Friendship.friendship_statuses[:rejected]), method: :patch %>
    <p>sent <%= time_ago_in_words(friendship.updated_at) %> ago </p>
    <h1></h1>
  <% end %>
<% end %>

app/views/friendships/rejected_requests.html.erb
<% if @rejected_requests.count==0 %>
  <p>No Users available </p>
<%end%>
<% @rejected_requests.each do |user| %>
  <%= turbo_frame_tag "rejectedpage_#{user.id}" do %>
    <%= image_tag url_for(user.avatar), class: "avatar" if user.avatar.attached? %>
    <%= link_to  user.name, account_path(user.id), method: :get, data: { turbo_frame: "_top" } %>
    <h1></h1>
    <% friendship = Friendship.where(reciver_id: current_user.id, sender_id: user.id).first %>
    <%= button_to "accept", friendship_path(friendship, status: Friendship.friendship_statuses[:accepted]), method: :patch %>
    <p>sent <%= time_ago_in_words(friendship.updated_at) %> ago </p>
    <h1></h1>
  <% end %>
<% end %>

app/views/friendships/update.turbo_stream.erb
<% if @update_success %>
  <% if @friendship.pending? %>
    <%= turbo_stream.replace "fbutton_#{ @friendship.reciver_id }" do %>
      <%= button_to "Pending" %>
    <% end %> 
  <% else %>
    <%= turbo_stream.remove turbo_reference_key(@friendship, request.referer) %>
    <% flash[:notice] = "Friend request #{Friendship.friendship_statuses.keys[params[:status].to_i] }" %>
  <% end %>
<%else %>
  <%= flash[:notice] = "Invalid User" %>
<% end %>

<%= render_turbo_stream_flash_message %>