config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :account, only: [ :show, :edit, :update ] do
    collection do
      get :cancel
      patch :privacy
    end
  end

  resources :posts, except: :show do
    collection do
      get :cancel
      get :my_posts
      get :onelayer
      post :daily_digest
    end
    resources :likes, only: [ :destroy, :create ]
  end

  resources :friendships, only: [ :index, :new, :create, :update ] do
    collection do
      get :pending_requests
      get :rejected_requests
      delete :cancel_request
      get :search
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy

  validates :title, length: { minimum: 1, message: "title cant be empty" }
  validates :description, length: { minimum: 1, message: "description cant be empty" }

  def liked_by(user)
    likes.find_by(user_id: user.id)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def show
  end
def index
  @posts=Post.all
  @user=User.all
  @like=Like.all
  @friends_id=Friend.where(user_id: current_user.id, status: "accepted").pluck(:friend_id)+Friend.where(friend_id: current_user.id, status: "accepted").pluck(:user_id)
  @user_posts=@posts.where(user_id: current_user.id).order(created_at: :desc)
  @other_posts=@posts.where(user_id: @friends_id).order(created_at: :desc)
  @posts=@user_posts+@other_posts
end
  def new
    @post=Post.new
  end
  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_index_path
    end
  end
  def create
    @user=current_user
    @post=@user.posts.create(post_params)
    if @post.save
      redirect_to post_index_path
    end
  end
  def edit
    @post=Post.find(params[:id])
  end
  def destroy
    @user=current_user
    @post=@user.posts.find(params[:id])
      if @post.destroy
        redirect_to post_index_path
      end
  end
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [ :edit, :update, :destroy ]

  def index
      @posts = case params[:filter]
      when "friends"
      current_user.my_feed
      when "friends_of_friends"
      Post.where(user_id: current_user.one_layer_friends_ids).includes(user: :avatar_attachment).order(created_at: :desc)
      else
      current_user.my_feed
      end
      @pagy, @posts = pagy(@posts, items: 10)
      respond_to do |format|
        format.html
        format.turbo_stream
      end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      render partial: "post", locals: { post: @post }
    else
      render partial: "form", status: :unprocessable_entity, locals: { post: @post, form_path: posts_path, form_method: :post }
    end
  end

  def edit; end

 def update
   if @post.update(post_params)
     render partial: "post", locals: { post: @post }
   else
     render partial: "form", status: :unprocessable_entity, locals: { post: @post, form_path: post_path(@post), form_method: :patch }
   end
 end


  def destroy
    @destroy_success = @post.destroy
  end

  def cancel
    respond_to do |format|
      format.html { redirect_to posts_path }
      format.turbo_stream
    end
  end

  def onelayer
    @posts = Post.where(user_id:  current_user.one_layer_friends_ids).includes(:user).order(created_at: :desc)
  end

  def daily_digest
    posts = current_user.my_feed.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    users_count = posts.select(:user_id).distinct.count
    posts_count = posts.count
    UserMailer.with(user: current_user, users_count: users_count, posts_count: posts_count).daily_digest.deliver_later
  end

private

  def post_params
    params.require(:post).permit(:title, :description)
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% is_edit = post.persisted? %>
<%= form_with model: post, url: form_path, method: form_method,
              html: {
                id: is_edit ? "edit-post-form-#{post.id}" : "new-post-form",
                onsubmit: is_edit ? "handleEditSubmit(event, #{post.id})" : "handleCreateSubmit(event)"
              } do |f| %>
  <%= f.label :title, placeholder: "title", class: "form_control" %>
  <%= f.text_field :title %>

  <%= f.label :description, placeholder: "description", class: "form_box" %>
  <%= f.text_field :description %>

  <%= f.submit is_edit ? "Update Post" : "Create Post" %>
<% end %>

app/views/posts/_post.html.erb
<%= turbo_frame_tag "post_#{post.id}" do%>
<div id="post-<%= post.id %>" class="post <%= 'highlight' if local_assigns[:highlight] %>">
  <div class="post-header">
    <div class="user-info">
      <%= image_tag url_for(post.user.avatar), loading: "lazy", class: "avatar" if post.user.avatar.attached? %>
      <%= link_to post.user.name, account_path(post.user), method: :get, data: { turbo_frame: "_top" } %>
    </div>

<div class="dropdown-wrapper"  x-data="{ showMenu: false }">
  <% if post.user_id == current_user.id %>
    <button x-show="!showMenu" @click="showMenu = true" style="background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;
    overflow: hidden;  ; color: black" >⋯</button>
    <div  x-show="showMenu" class="dropdown " x-transition @click.outside="showMenu = false">
      <%= button_to "✏️", edit_post_path(post), method: :get %>
      <button data-post-id="<%= post.id %>" onclick="handleDeletePost(event)">🗑️</button>
    </div>
  <% end %>
</div>
  
  </div>
  <% if local_assigns[:trending_score] %>
    <p>Trending Score: <%= trending_score %></p>
  <% end %>

  <h3 style = "color: #0889bd; font-size: 2rem; margin: 10px; margin-bottom: 15px" > <%= post.title %> </h3>
  <p style="margin: 0;color: black; margin: 15px;line-height: 22px" ><%= post.description %></p>
  <p style="color: grey;display: inline;margin: 15px"><%= (post.created_at.strftime("%I:%M %p   %d/%m/%Y")) %></p>

  <%= render partial: "likes/like", locals: { post: post } %>
</div>
<%end%>

app/views/posts/cancel.turbo_stream.erb
<%= turbo_stream.remove Post.new %>

app/views/posts/create.turbo_stream.erb
<% if @post.persisted? %>
  <%= turbo_stream.prepend "post", partial: "posts/post", locals: { post: @post, highlight: true } %>
  <%= turbo_stream.replace Post.new do %>
    <%= turbo_frame_tag Post.new do %>
      <%= button_to "Add a post", new_post_path, data: { turbo_frame: dom_id(Post.new) }, method: :get %>
    <% end %> 
  <% end %>
<% else %>
  <%= turbo_stream.replace Post.new, partial: "posts/form", locals: { post: @post } %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<% if @destroy_success %>
  <%= turbo_stream.remove "post_#{@post.id}" %>
<%else %>
  <% flash[:notice] = @post.errors.full_messages.to_sentence %>
<% end %>

<%= render_turbo_stream_flash_message %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post_#{@post.id}" do %>
  <%= render partial: "form", locals: { post: @post, form_path: post_path, form_method: :patch } %>
<% end %>

app/views/posts/index.html.erb
<%= form_with url: posts_path, method: :get, local: true do |form| %>
  <%= form.label :filter, "Show posts from:" %>
  <%= form.select :filter, options_for_select([["Friends", "friends"], ["Friends of Friends", "friends_of_friends"]], params[:filter]), {}, { onchange: "this.form.submit();" } %>
<% end %>
<div x-data="{ open: false }" x-init="window.addEventListener('post-created', () => { open = false })">
  <button type="button" @click="open = true" class="btn">Add a post</button>
  <div  x-show="open" >
    <%= render partial: "form", locals: { post: Post.new, form_path: posts_path, form_method: :post} %>
  </div> 
  <button x-show = "open" @click="open = false" >close</button>   
</div> 
<div id="posts-list">
  <%= render @posts %>
</div>

<% if @pagy.next.present? %>
  <%= turbo_frame_tag "next_page", src: posts_path(page: @pagy.next, format: :turbo_stream), loading: :lazy do %>
    <div style="text-align: center; padding: 1em; font-weight: bold; color: black;">Loading more posts...</div>
  <% end %>
<% end %>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append "posts-list" do %>
  <%= render @posts %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "next_page" do %>
    <%= turbo_frame_tag "next_page", src: posts_path(page: @pagy.next, format: :turbo_stream), loading: :lazy do %>
      <div style="text-align: center; padding: 1em; font-weight: bold; color: black;">Loading more posts...</div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/my_posts.html.erb
 <%= render current_user.posts %>

app/views/posts/new.html.erb
<%= turbo_frame_tag @post do %>
  <%= render partial: "form", locals: { post: @post, form_path: posts_path, form_method: :post} %>
<% end %>

app/views/posts/onelayer.html.erb
<%= turbo_frame_tag "post" do %>  
  <%= render @posts %>
<% end %>

app/views/posts/update.turbo_stream.erb
<% if @update_success %>
  <%= turbo_stream.replace "post_#{@post.id}" do %>
    <%= render @post %>
  <% end %>
<%else %>
  <% flash[:notice] = "Your are not authorized" %>
<% end %>
<%= render_turbo_stream_flash_message %>