config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :account, only: [ :show, :edit, :update ] do
    collection do
      get :cancel
      patch :privacy
    end
  end

  resources :posts, except: :show do
    collection do
      get :cancel
      get :my_posts
      get :onelayer
      post :daily_digest
    end
    resources :likes, only: [ :destroy, :create ]
  end

  resources :friendships, only: [ :index, :new, :create, :update ] do
    collection do
      get :pending_requests
      get :rejected_requests
      delete :cancel_request
      get :search
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
end

app/views/trending/index.html.erb
<h1>Trending's page </h1>
<% @h.each do |key,value| %>
    <p>Trending Value: <%=value%> </p>

    <% p=@allp.find(key) %>
    <%= link_to  (
        p.user.username
        ), account_path(p.user_id) , method: :get %>
    <% if p.user.avatar.attached? %>
        <img src="<%=url_for(p.user.avatar)%>" class="avatar" />
    <%end%>
    <p style="block:flex;" >Title:<%= p.title %></p>
    <%= time_ago_in_words(p.created_at) %>
    <p>description:<%= p.description %></p>
    <%=turbo_frame_tag "like_#{p.id}" do %>
        <% if p.like.exists?(user_id:current_user) %>
            <%= button_to "Unlike",post_like_path(post_id: p.id,id: p.like.find_by(user_id: current_user.id).id),method: :delete %>
        <%else%>
             <%= button_to "Like",post_likes_path(p.id),method: :post %>
        <%end%>
        <%= render partial: "likes/like",locals: {post: p} %>
    <%end%>
<%end%>