config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :account, only: [ :show, :edit, :update ] do
    collection do
      get :cancel
      patch :privacy
    end
  end

  resources :posts, except: :show do
    collection do
      get :cancel
      get :my_posts
      get :onelayer
      post :daily_digest
    end
    resources :likes, only: [ :destroy, :create ]
  end

  resources :friendships, only: [ :index, :new, :create, :update ] do
    collection do
      get :pending_requests
      get :rejected_requests
      delete :cancel_request
      get :search
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root to: "home#index"
end

app/views/layouts/_flash.html.erb
<%= turbo_frame_tag "flash" do %>
  <% flash.each do |flash_type, message| %>
    <div class="notice">   
      <p><%= message %></p>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-container">
    <ul class="nav-left">
      <li><%= link_to "Home", "/" %></li>
      <% if current_user %>
        <li><%= link_to "Posts", posts_path %></li>
      <% end %>
    </ul>

    <ul class="nav-right" x-data="{ open: false }">
      <% if current_user && current_user.avatar.attached? %>
        <li class="dropdown-wrapper" x-data="{ open: false }">
        <%= image_tag url_for(current_user.avatar), class: "avatar", "@click": "open = !open" %>
        <div class="dropdown" x-show="open" @click.outside="open = false">
          <%= link_to "Account", account_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "My Posts", my_posts_posts_path, class: "dropdown-item" %>
          <%= link_to "Friends", friendships_path, class: "dropdown-item" %>
          <%= button_to "Log out", destroy_user_session_path,method: :delete,  class: "dropdown-item" %>
        </div>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Catchup1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <link rel="stylesheet" href="https://unpkg.com/simpledotcss/simple.min.css">
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <div class="main-container">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    
      <%= yield %>
    </div>
  </body>
</html>